/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__3 = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'photoId' : IDL.Text,
});
export const T__2 = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'zoneId' : IDL.Text,
  'photoId' : IDL.Text,
});
export const T__1 = IDL.Record({
  'clockOut' : IDL.Opt(T__3),
  'clockIn' : IDL.Opt(T__2),
});
export const T = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'radius' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkplaceZone' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clockIn' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text, IDL.Text], [], []),
  'clockOut' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [], []),
  'deleteWorkplaceZone' : IDL.Func([IDL.Text], [], []),
  'getAllCurrentlyClockedIn' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T__1))],
      ['query'],
    ),
  'getAttendanceForTodayOrRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Principal, T__1))],
      ['query'],
    ),
  'getAttendanceRecords' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Int],
      [IDL.Vec(T__1)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentClockInStatus' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listWorkplaceZones' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'purgeOldRecords' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__3 = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'photoId' : IDL.Text,
  });
  const T__2 = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'zoneId' : IDL.Text,
    'photoId' : IDL.Text,
  });
  const T__1 = IDL.Record({
    'clockOut' : IDL.Opt(T__3),
    'clockIn' : IDL.Opt(T__2),
  });
  const T = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'radius' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkplaceZone' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clockIn' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'clockOut' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [], []),
    'deleteWorkplaceZone' : IDL.Func([IDL.Text], [], []),
    'getAllCurrentlyClockedIn' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T__1))],
        ['query'],
      ),
    'getAttendanceForTodayOrRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Principal, T__1))],
        ['query'],
      ),
    'getAttendanceRecords' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Int],
        [IDL.Vec(T__1)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentClockInStatus' : IDL.Func([], [IDL.Opt(T__1)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listWorkplaceZones' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'purgeOldRecords' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };