/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface T {
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'radius' : number,
}
export interface T__1 { 'clockOut' : [] | [T__3], 'clockIn' : [] | [T__2] }
export interface T__2 {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'zoneId' : string,
  'photoId' : string,
}
export interface T__3 {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'photoId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorkplaceZone' : ActorMethod<[string, number, number, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clockIn' : ActorMethod<[number, number, string, string], undefined>,
  'clockOut' : ActorMethod<[number, number, string], undefined>,
  'deleteWorkplaceZone' : ActorMethod<[string], undefined>,
  'getAllCurrentlyClockedIn' : ActorMethod<[], Array<[Principal, T__1]>>,
  'getAttendanceForTodayOrRange' : ActorMethod<
    [bigint, bigint],
    Array<[Principal, T__1]>
  >,
  'getAttendanceRecords' : ActorMethod<
    [Principal, bigint, bigint],
    Array<T__1>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentClockInStatus' : ActorMethod<[], [] | [T__1]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listWorkplaceZones' : ActorMethod<[], Array<T>>,
  'purgeOldRecords' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];